### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by Natr1x** [krakend/krakend-documentation#184]
Not sure where to post this so I am sorry if this is not the right place but I kind of find the documentation to be borderline unreadable because of the lack of dark mode or something similar.

A minor issue of course since there are browser addons for this sort of thing and it seems to be a theme among reverse proxy/api gateway sites to generally blind their visitors. But I have been looking around for an api gateway solution all day now and if any one of the options would have had a readable colour palette then I would have picked that one.

**Comment by alombarte** [comment]
Hello @Natr1x , thanks for your feedback.

**Comment by alombarte** [comment]
Hi @Natr1x, I'm just letting you know that we are actively working on offering a dark version of the website. As you might guess, this is not a two-hour job but is being worked right now.
Thanks

**Comment by obokaman-com** [comment]
Hi @Natr1x,

It took some time, but we’ve just launched our new website redesign today, which includes the long-awaited dark mode for the documentation. This feature was inspired by suggestions like yours, so thanks for your contribution! We hope you'll enjoy the new dark mode as well as other visual improvements we made along the way.

Feel free to check it out and let us know what you think!

Best regards,
