### ISSUE TITLE
Documentation about roles in jwt validation is misleading

### ISSUE THREAD

**Issue by maksutspahi** [krakend/krakend-documentation#201]
Hello,
Here about roles array: https://www.krakend.io/docs/authorization/jwt-validation/#:~:text=realm_access.roles.-,roles,-array says that:

> When set, the JWT token not having at least one of the listed roles is rejected.

But below that at validation part: https://www.krakend.io/docs/authorization/jwt-validation/#validation-process

> The configuration allows you to define the set of required roles. For example, a user who passes a token with roles A and B, can access an endpoint requiring "roles": ["A","C"] as it has one of the required options (A).

These 2 sentences are exactly the opposite. I think the second one is true which is (at least one role match can get endpoint access) where I can confirm via krakend-jose code ( https://github.com/krakend/krakend-jose/blob/master/jose.go#L86 )

Thank you

**Comment by alombarte** [comment]
How are these sentences opposed?

> the JWT token not having at least one of the listed roles is rejected.
Says that the token must contain one or more roles of the list

> The configuration allows you to define the set of required roles. For example, a user who passes a token with roles A and B, can access an endpoint requiring "roles": ["A","C"] as it has one of the required options (A).
Says that a token which contains A can access because it contains one or more roles of the list.

How would you rephrase both? I don't understand how are you reading this.

**Comment by maksutspahi** [comment]
Ok I think I misread it in the first place sorry, we can close this issue.
