### ISSUE TITLE
Certain headers (Content-Type) have undocumented complications

### ISSUE THREAD

**Issue by ethanpooley** [krakend/krakend-documentation#224]
It appears that certain headers, including Content-Type, are subject to undocumented complications when one attempts to modify them. For example, the following backend configuration resulted in an empty Content-Type header being sent to the backend. Reversing the _order_ of the two modifiers fixed this. My assumption is that attempts to alter the Content-Type header are tested for validity against the current body. So, the body must first be changed to something valid for the future Content-Type. This left me wondering if there are other such complications, and how users can discern them.

```json
"extra_config": {
    "modifier/martian": {
        "fifo.Group": {
            "scope": ["request"],
            "modifiers": [
                {
                    "header.Modifier": {
                        "scope": [ "request" ],
                        "name": "Content-Type",
                        "value": "application/x-www-form-urlencoded"
                    }
                },
                {
                    "body.Modifier": {
                        "scope": [ "request" ],
                        "body": "c29tZXZhcj1zb21ldmFsJnNvbWVvdGhlcnZhcj1zb21lb3RoZXJ2YWw="
                    }
                }
            ]
        }
    }
}
```

**Comment by kpacha** [comment]
you are right, the `content-type` configuration value is not documented.

**Comment by alombarte** [comment]
Added to the documentation. Thanks for reporting!
